"""fix_eliminated fiel

Revision ID: 4ad24bd62f90
Revises: f00380b94540
Create Date: 2025-11-27 18:31:37.811353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad24bd62f90'
down_revision: Union[str, Sequence[str], None] = 'f00380b94540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pk_sequencial')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pk_sequencial', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
