"""add field password

Revision ID: d9a2b2556ce8
Revises: 099a59a021bb
Create Date: 2025-11-27 16:46:27.247370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a2b2556ce8'
down_revision: Union[str, Sequence[str], None] = '099a59a021bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pk_sequencial', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pk_sequencial')
    # ### end Alembic commands ###
